{% set name = "influxdb_client" %}
{% set version = "1.21.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/11/4e/56bb9316c41635988c5e98c30490c95895b5cea71e18ebd848e2224f77e6/influxdb_client-1.21.0.tar.gz
  sha256: f3c9b51858ee3f5d219f145b4f71518ae5a0284c85d03f88940c143a63e6b8ce

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - setuptools
#    - rx >=3.0.1
#    - certifi >=14.05.14
#    - six >=1.10
#    - python_dateutil >=2.5.3
#    - setuptools >=21.0.0
#    - urllib3 >=1.15.1
#    - pytz >=2019.1

about:
  home: https://github.com/influxdata/influxdb-client-python
  license: MIT License
  license_file: ../LICENSE
  summary: The Python client library for the InfluxDB 2.0.
  dev_url: https://github.com/influxdata/influxdb-client-python

