{% set name = "influxdb_client" %}
{% set version = "1.30.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/c5/c1/02a50d9c2bfa450f4ae807e8be83f72f0b79c447e9762dc8337c545fdf5e/influxdb_client-1.30.0.tar.gz
  sha256: 691acd05d3ca205c1c561991e1d7888d65706feb0a44076f2a22eb572aed9926

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - setuptools

about:
  home: https://github.com/influxdata/influxdb-client-python
  license: MIT License
  license_file: ../LICENSE
  summary: The Python client library for the InfluxDB 2.0.
  dev_url: https://github.com/influxdata/influxdb-client-python

