{% set name = "influxdb_client" %}
{% set version = "1.40.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/63/11/07ed82352a28e4e8b623a487337befec77d5bd18293dcc940d769e633f82/influxdb_client-1.40.0.tar.gz
  sha256: 027f970af1518479d8806f1cdf5ba20280f943e1b621c2acdbf9ca8dc9bdf1cb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - setuptools

about:
  home: https://github.com/influxdata/influxdb-client-python
  license: MIT License
  license_file: ../LICENSE
  summary: The Python client library for the InfluxDB 2.0.
  dev_url: https://github.com/influxdata/influxdb-client-python

