{% set name = "influxdb_client" %}
{% set version = "1.29.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/35/91/65a16c8fcb2897007c5b130ed723c85e01841c8561004c30020476f34cac/influxdb_client-1.29.0.tar.gz
  sha256: 4f56622d9f63f3eea22859f3a53564f803f422a10fdd421d839abc13e3fe36f7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - setuptools

about:
  home: https://github.com/influxdata/influxdb-client-python
  license: MIT License
  license_file: ../LICENSE
  summary: The Python client library for the InfluxDB 2.0.
  dev_url: https://github.com/influxdata/influxdb-client-python

