{% set name = "influxdb_client" %}
{% set version = "1.20.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.python.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: da734bb25e7064e03bf9699de502b4e02ef0304cddac7cb56cbd9d5d0c3a3bcd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - setuptools
#    - rx >=3.0.1
#    - certifi >=14.05.14
#    - six >=1.10
#    - python_dateutil >=2.5.3
#    - setuptools >=21.0.0
#    - urllib3 >=1.15.1
#    - pytz >=2019.1

about:
  home: https://github.com/influxdata/influxdb-client-python
  license: MIT License
  license_file: ../LICENSE
  summary: The Python client library for the InfluxDB 2.0.
  dev_url: https://github.com/influxdata/influxdb-client-python

