{% set name = "influxdb_client" %}
{% set version = "1.36.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/ad/c5/2a8c6be01233a523b0b585b343b00acc79e637f641e360c05aaaaa4a5c02/influxdb_client-1.36.1.tar.gz
  sha256: 59654af4f7133f0ecf916411935b50f42e5c4bc125d218e193848f3615b57bfc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - setuptools

about:
  home: https://github.com/influxdata/influxdb-client-python
  license: MIT License
  license_file: ../LICENSE
  summary: The Python client library for the InfluxDB 2.0.
  dev_url: https://github.com/influxdata/influxdb-client-python

