{% set name = "influxdb_client" %}
{% set version = "1.34.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/c6/c0/d3d72e27c9b77da94344fd27b29fa1b8708be3f3b63805cb24c1ea63898c/influxdb_client-1.34.0.tar.gz
  sha256: e5691e50367ffa7768e3ff74c857cb9c3df2eba7a82526f176394ae4ee1fbd48

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - setuptools

about:
  home: https://github.com/influxdata/influxdb-client-python
  license: MIT License
  license_file: ../LICENSE
  summary: The Python client library for the InfluxDB 2.0.
  dev_url: https://github.com/influxdata/influxdb-client-python

