{% set name = "influxdb_client" %}
{% set version = "1.33.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/fd/51/30168a2c9266e479f8f64e85f91221b9be66ea85e0ff645fcb1d4175f8e0/influxdb_client-1.33.0.tar.gz
  sha256: 45f6a1763804a19b972890daf4c5f0bd2d3ae2f202b86451c579e09dcadd30e6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - setuptools

about:
  home: https://github.com/influxdata/influxdb-client-python
  license: MIT License
  license_file: ../LICENSE
  summary: The Python client library for the InfluxDB 2.0.
  dev_url: https://github.com/influxdata/influxdb-client-python

